- tests/CreatesApplication.php
I understand the tests aren't all passing at this time, but this is now standard practice for speeding up test execution.
> Add Hash::setRounds(4) to CreatesApplication trait to speed up tests

- tests/Feature/AddAvatarTest.php
- tests/Feature/BestReplyTest.php
- tests/Feature/CreateThreadsTest.php
- tests/Feature/FavoritesTest.php
- tests/Feature/LockThreadsTest.php
- tests/Feature/MentionUsersTest.php
- tests/Feature/NotificationsTest.php
- tests/Feature/ParticipateInThreadsTest.php
- tests/Feature/ProfilesTest.php
- tests/Feature/ReadThreadsTest.php
- tests/Feature/RegistrationTest.php
- tests/Feature/SubscribeToThreadsTest.php
- tests/Feature/TrendingThreadsTest.php
- tests/Unit/ActivityTest.php
- tests/Unit/ChannelTest.php
- tests/Unit/ReplyTest.php
- tests/Unit/ThreadTest.php
- tests/Unit/UserTest.php
Should improve performance when running test suites.
> Use RefreshDatabase trait instead of DatabaseMigrations

- LICENSE.md
This PR adds the MIT license to this project. For me, MIT is the way to go for any OSS project, but you can always choose another from [GitHub's ChooseALicense page](https://choosealicense.com).
Closes #25 
:octocat:
> License under MIT

- phpunit.xml
This PR updates the PHPUnit configuration file to warn when a test didn't perform assertions.
:octocat:
> Warn when a test doesn't assert anything

- routes/web.php
- tests/Feature/AddAvatarTest.php
- tests/Feature/FavoritesTest.php
- tests/Feature/NotificationsTest.php
- tests/Feature/ParticipateInThreadsTest.php
- tests/Feature/ProfilesTest.php
- tests/Feature/ReadThreadsTest.php
- tests/Feature/ReputationTest.php
Nothing special, just added names to all routes.
I haven't touched the tests that used $thread->path() for obvious reasons :)
> Adding name to all routes and refactoring some tests to use them

- tests/Unit/ThreadTest.php
a_thread_notifies_all_registered_subscribers_when_a_reply_is_added was broken after adding reputation logic in Reply.php's boot method.
Because user_id was hardcoded to 999 in the unit test, it attempted to add reputation points to a user that didn't exists. I changed it so that a new user is created when the reply is created in the test.
Also, VS Code really likes to reformat code that doesn't need it sometimes ☺️
> fix broken test in ThreadTest

- tests/Feature/ReputationTest.php
I believe that the story being told by this test should be more explicit - there are two distinct users, the reply owner and the authenticated user who favorites and unfavorites the reply.
> Make it clear that the reply owner gets the reputation award reduction

- resources/views/admin/channels/index.blade.php
While its okay to use count(), why don't we use laravel's own collection method's `->count()`.
Also, I noticed that in PHP 7.2 there is a warning saying, 
> count(): Parameter  must be an array or an object that implements Countable
> Use Laravel's collection method 

- resources/assets/js/components/Reply.vue
- resources/views/threads/_question.blade.php
After your refactor the ref property is no more needed outside from the new highlight component.
> Removed obsolte ref properties remained from refactoring

- resources/assets/js/components/ChannelDropdown.vue
I just renamed a computed property from filteredThreads to filteredChannels.
I know, it's a small change but I think this makes more sense.
> Renamed computed property for filtered channels

- app/Http/Controllers/PinnedThreadsController.php
- app/Http/Controllers/ThreadsController.php
- app/Thread.php
- database/migrations/2017_03_15_175959_create_threads_table.php
- resources/assets/js/pages/Thread.vue
- resources/views/threads/_list.blade.php
- resources/views/threads/show.blade.php
- routes/web.php
- tests/Feature/PinThreadsTest.php
Many forums have the ability to 'Pin' threads to the top of a list of threads. This PR introduces that feature,
- Administrators can pin and unpin threads.
- Pinned threads are displayed at the top of the Thread listings with a pin icon.
If anybody has any thoughts on `tests/Feature/PinThreadsTest@pinned_threads_are_listed_first()` i'd like to hear them. I'm not 100% happy with how its implemented.
> An administrator can 'Pin' Threads

- app/Http/Controllers/Auth/RegisterController.php
Trying to register a user with a name that is already registered throws a QueryException since the name field in users table has a unique constraint. This pull request fixes it by adding the unique validation for name field while registering a user.
> Adds uniqueness validation for user's name during registration

- app/Http/Controllers/ThreadsController.php
- tests/Feature/CreateThreadsTest.php
While a user will not see archived channels on the front end when creating threads, they can submit a POST request behind the scenes with an archived channel id and it will work.  This commit blocks that, which I believe is the intended behavior.
> Disallow new threads in archived channels

- resources/assets/js/components/NewReply.vue
- resources/assets/js/components/Wysiwyg.vue
Currently it looks very flat. This is a temporary fix while the design stuff comes along. 🤠
I also made the wysiwyg editor a big bigger.
> Change the look of the new reply section when viewing a thread.

- resources/views/admin/channels/index.blade.php
This may just be a matter of opinion, but to me archiving is almost akin to a soft delete; we want to remove the channel from use, but keep the content around for historical purposes.
Using the danger class on the table row is, in my opinion, slightly more semantic and serves as a better indicator that the channel is archived.
> Use more semantic class to indicate archived channels

- app/Http/Controllers/Admin/ChannelsController.php
- resources/views/admin/channels/index.blade.php
This PR simply optimisees queries on the Admin Channels index view by (i) eager-loading threads count rather than whole Thread objects and (ii) replacing N+1 queries in the view with the eager-loaded count
> Use withCount to optimise queries

- app/Thread.php
- tests/Feature/Admin/ChannelAdministrationTest.php
right now, call 'path()' on a thread in an archived channel will throw an error. 
This PR fixes it.
> fix a bug when trying to get path of a thread in an archived channel.

- app/Channel.php
- app/Http/Controllers/Admin/ChannelsController.php
- tests/Unit/ChannelTest.php
This is a fairly straight forward refactor to pull the sorting out of the 'active' global scope, since the two issues are unrelated.
This lets us test and refactor the sorting of the channels independent of the active/archived state. As well we don't have the somewhat strange situation in Admin\ChannelsController where we're striping the sort order off with withoutGlobalScopes() only to add it right back on. 
I created a macro on the Eloquent Collection to cleanly test sort order (ala Adam W.). This could be pulled up into TestCase if its useful in other tests.
> Separate sorted and active global scopes

- app/Providers/RouteServiceProvider.php
- routes/web.php
- tests/Feature/Admin/ChannelAdministrationTest.php
Not sure if the `RouteServiceProvider` approach is really the cleanest, but I think I prefer it to doing `withoutGlobalScopes()` in two places.
Cheers!
> Admins can activate archived channels - resolves #157.

- app/Providers/AppServiceProvider.php
I've removed the `$trending` param on the boot method as it is no longer used.
> Remove unneeded param on App Service Provider

- resources/assets/js/components/Reply.vue
When you click on reply creator's name, it redirects you to `/profile/name` instead of `/profile/username`. This PR fixes the issue.
> Quick Bug Fix: Reply now references correct dynamic link to user's profile

- app/HasReputation.php
This method was added when the Trait HasReputation was created but is
never used in the application or tests.
> Remove unused clearReputation method.

- app/Console/Commands/InstallCommand.php
During installation, if I leave blank for no password
in the file you will have `NULL`
and for the migration we expect to have `null` for no password
so migration will failed because the credentials will be NULL password instead of no password at all.
> Fix password database empty during install

- resources/views/modals/all.blade.php
- resources/views/sidebar.blade.php
I've updated the create a new thread button to only be accessible to users that have been confirmed, I've also updated the `all.blade.php` to be `includeWhen`. I was also tempted to do the same for the login and register modals, but I thought that'd be best to do in a separate PR.
> Don't show create new thread modal for non confirmed users

- resources/views/threads/create.blade.php
E.g. user does not provide a title or click the reCAPTCHA when creating a new thread.
> Save content of the body input if validation fails

- app/Providers/AppServiceProvider.php
- database/factories/ModelFactory.php
- database/seeds/SampleDataSeeder.php
- database/seeds/UsersSeeder.php
- resources/views/threads/_question.blade.php
This PR changes the seeders to create a more realistic feeling forum. 
- Four users are created.
- Realistic channels are created (Eloquent, Laravel Mix, PHP, VueEx and VueJS )
- The seeded threads are assigned to the existing channels and users (currently new users and channels are created for each thread).
- Each thread is seeded with a visit count
- A seeded thread may be locked (there is a 15% chance a thread will be created locked)
- Thread creation activity is recorded so that user profiles are correct (currently seeded users have no activity)
> Improve seeding with realistic users, channels, visit counts and activity.

- resources/views/layouts/app.blade.php
Because the modal component is loaded through JavaScript when the page loads the `modals.all` partial renders only the raw HTML until the JavaScript is loaded.
Wrapping the `@inclue()` method in a `div` with the `[v-cloak]` attribute uses CSS to hide this from view until the JavaScript has finished loading as described here https://vuejs.org/v2/api/#v-cloak.
> Wrap the Modals in a div with the v-cloak to prevent the momentary "blink"

- app/Reply.php
- tests/Feature/ReputationTest.php
The user should lose his best reply award points and his points for reply creation when the reply is deleted.
> Best reply award should be lost when reply is deleted

- app/Activity.php
- app/Http/Controllers/ProfilesController.php
- app/Reply.php
- resources/assets/js/app.js
- resources/assets/js/components/Activities.vue
- resources/assets/js/components/ActivityFavorite.vue
- resources/assets/js/components/ActivityLayout.vue
- resources/assets/js/components/ActivityReply.vue
- resources/assets/js/components/ActivityThread.vue
- resources/assets/js/components/Paginator.vue
- resources/assets/js/mixins/activity.js
- resources/views/profiles/show.blade.php
- routes/web.php
This PR is a response to @JeffreyWay who asked for a pull request that styled the user profile page in the Laracasts video https://laracasts.com/series/how-to-manage-an-open-source-project/episodes/20.
🚨 **Note** this is **work in progress**.
- there are a couple of tests to fix.
- there are a couple of tests to implement.
Having said that, I think its in a relatively good place. @JeffreyWay you are free to merge if you think its _good enough_ for you to work with.
⚠️ Note that in  `.resources/assets/sass/_timeline.scss` there are a small number of styles for the timeline that can't be implemented via tailwind yet. At least I couldn't work out how 🤷‍♂️ 
**Features**
- Style the user activity following existing Council design precedence.
- On all activities show the amount of XP gained.
- …
> [ wip ] — Style the users profile page

- resources/views/threads/_question.blade.php
The form for editing a thread shows for a split second when loading the page (Even when visiting as a guest).
The `v-cloak` is a quick fix for this.
> Add v-cloak to prevent the form from showing on page load.

- tests/TestCase.php
This PR allows us to enable foreign key constraints dynamically. When running the command:
DB::statement('PRAGMA foreign_keys=on;');
it will enable foreign key constraints only on sqlite. The intended change will make it dynamic, and will not be specific to sqlite etc.
Schema::enableForeignKeyConstraints();
> Enable foreign key constraints dynamically

- resources/assets/js/components/Activities.vue
- resources/assets/js/components/ActivityLayout.vue
- resources/assets/sass/_timeline.scss
- resources/assets/sass/app.scss
@JeffreyWay First off, sorry for the state of the profile styling PR. Yes, it was work in progress but I had completely screwed up the branch in an attempt to rebase it. I had thought it was fixed but clearly not. 
As you mentioned in the Laracasts episode, you were confused about the missing `_timeline.scss` file. This PR fixes that. 
- add missing `_timeline.scss` file.
- add back required markup to Vue components.
**Note** I wasn't sure whether to put the styles in `app.scss`,  or in `components/timeline.scss. Not a big issue but I thought you may want to try and figure out if its possible to implement in a nicer way so I just left it.
> Add back missing blue dots to profile activity.

- database/seeds/SampleDataSeeder.php
Nothing really special here; just updating some wording and code references.
I've found a very strange bug though. If you remove the `'archived' => false` reference from the model factory and then run the test suite again, 2 errors will come up saying "Failed asserting that null is false.", `null` referring to the `archived` property on a Channel instance, even though it's set to `false` by default in the migration file.
Using `dd()` to debug shows that it's not in the attributes list at all when running tests, but works perfectly fine in development (MySQL). I'm guessing this might have something to do with SQLite? Or maybe I'm just missing something.
> Adjust DB seeder channels call

- resources/assets/js/components/Dropdown.vue
- resources/assets/js/components/UserNotifications.vue
- resources/assets/js/mixins/activation.js
If you accidentally hover over the wrong button in the navigation, it will overlap the button you want to interact with.
Adding a `100ms` delay before activating or deactivating the component it will be more forgiving to the user.
> UX fix - Delay hover activation in navigation

- resources/views/layouts/app.blade.php
When content does not fill the whole page the container is not using the full height.
As-Is situation on the admin page
This PR will result in
Feedback is welcome if more efficient solutions exist.
> Fix layout height when content does not fill full height.

- app/Http/Controllers/Api/LeaderboardController.php
- app/Http/Controllers/LeaderboardController.php
- app/User.php
- resources/assets/js/app.js
- resources/assets/js/components/Leaderboard.vue
- resources/views/leaderboard/index.blade.php
- resources/views/sidebar.blade.php
- resources/views/svgs/icons/leaderboard.blade.php
- routes/web.php
- tests/Feature/LeaderboardTest.php
This PR introduces a rudimentary user 'leaderboard' that lists the top 10 users in descending order of reputation. 
- A 'Leaderboard' link is added to the main left nav.
- A simple leaderboard api endpoint is introduced.
- A new `Leaderboard.vue` component responsible for calling the leaderboard api and rendering the results is introduced.
**Note:** The file `resources/views/svgs/icons/leaderboard.blade.php` is not an SVG file. It is simple html with tailwind styling but an SVG can be added at a later date.
- Add more metadata to the entries on the leaderboard page, for example, number of threads, number of replies and number of best replies. 
I considered adding these but quickly realised that it was a fairly big job. It would require adding accessors on models (to calculate the data) …
> Initial Leaderboard Implementation
