- app/Http/Controllers/Auth/LoginController.php
- app/Http/Controllers/Auth/RegisterController.php
This PR resolves #6 
Another option is to use the `Route::redirect('/home', '/threads')` method.
> redirects to the /threads route after a user has logged in or registered

- readme.md
> Add migration to step 2.

- database/seeds/DatabaseSeeder.php
- database/seeds/SampleDataSeeder.php
- database/seeds/UsersSeeder.php
This seeders will generate standard John Doe acccount, 10 fake channels and 50 fake threads.
> Default seeders instead of tinkering

- database/seeds/DatabaseSeeder.php
> Chain seeders

- database/seeds/DatabaseSeeder.php
> Fix typo in DatabaseSeeder

- public/js/app.js
- resources/assets/js/components/SubscribeButton.vue
> Avoid mutating props while subscribing to a thread.

- app/Http/Controllers/RepliesController.php
- routes/web.php
This PR adds a check to prevent replies from users who haven't confirmed their email adress.
Closes #51 
:octocat:
> Require email confirmation to reply

- readme.md
Fixes #21 
* Add information on how to install assets
* Add yarn as default give hint about npm replacement
> Fix #21 update readme to include assets install

- app/Console/Commands/InstallCommand.php
> Add cache:clear to the install command

- readme.md
> Removed a dot from Step 2

- app/HasReputation.php
- app/Http/Controllers/FavoritesController.php
- app/Reply.php
- app/Reputation.php
- app/Thread.php
- app/User.php
- config/council.php
- tests/Feature/ReputationTest.php
Moved reputation points declaration to council.php config file and gain/lose methods to the HasReputation trait. I obviously refactored the related tests as well :)
Fix #87
> Reputation points refactor

- app/Console/Commands/InstallCommand.php
- tests/Console/InstallCommandTest.php
Ask for database port on installation process
> Resolve #99

- package.json
- public/css/app.css
- public/js/app.js
- resources/assets/js/bootstrap.js
- resources/assets/js/components/Reply.vue
- resources/assets/js/pages/Thread.vue
- resources/views/threads/_question.blade.php
adds syntax highlight using highlight.js with "foundation" style.
> Add Syntax Highlight - resolves #29

- resources/assets/js/app.js
- resources/assets/js/components/ChannelDropdown.vue
- resources/views/layouts/nav.blade.php
This PR adds a small Vue Component that adds a dropdown filter component for channels to the nav bar.
> Add channel filter dropdown vue component

- config/purify.php
- resources/views/threads/_list.blade.php
- Add syntax highlighting to the browse pages.
- Add `<blockquote>` to the list of Purify's acceptable tags.
> Syntax highlighting updates.

- app/Console/Commands/InstallCommand.php
- tests/Console/InstallCommandTest.php
Resolves #72 
Not sure if that's the best way to tackle the problem, but it's not that bad either.
> Fixed a problem with migrations executed during installation

- app/Http/Controllers/Admin/ChannelsController.php
- resources/views/admin/channels/_form.blade.php
- resources/views/admin/channels/create.blade.php
- resources/views/admin/channels/edit.blade.php
- resources/views/admin/channels/index.blade.php
- routes/web.php
- tests/Feature/Admin/ChannelAdministrationTest.php
This addresses the edit portion of issue #85.
Not sure on how the deletion should be handled at this stage.
> Issue #85: Add the ability to edit existing channels

- app/Thread.php
Skip subcription query if users is anonymous
> Resolve #150

- app/Console/Commands/InstallCommand.php
Hello Jeffrey,
Thanks for all your videos.
Please find my very little contribution to your project.
When I run council:install and I give my password for the database, it's never saved in the env file.
> Fix password never saved

- package-lock.json
- package.json
- resources/assets/js/bootstrap.js
This goes together with #174 (Laravel 5.6 upgrade)
> Upgrade to Laravel 5.6 NPM dependiencies

- .env.example
- app/Reply.php
- app/Thread.php
- composer.json
- composer.lock
- config/app.php
- config/hashing.php
- config/logging.php
- tests/Feature/ParticipateInThreadsTest.php
- tests/Feature/PinThreadsTest.php
- Updated composer dependencies and config files.
- Fixed bug - when Best Reply is deleted its `id` is not unset from thread `best_reply_id`.
- Fix test to reflect Laravel 5.6 changes. 201 status code is returned for newly created models instead of 200
> Upgrade to Laravel 5.6

- app/Http/Controllers/Auth/LoginController.php
- resources/assets/js/components/Login.vue
We assumed that in a successful login request we would redirect to the same url. Although the controller contains a property as to where we would redirect our application in successful login. So this commit makes our front end redirect on the location the login controller specifies.
> Use the redirectTo property of the LoginController, to decide where to redirect after a successful login.

- routes/web.php
This PR removes leading slashes. PR #217 adds missing leading slashes.
> Remove leading slashes in routes/web.php - resolves #216

- app/Http/Controllers/Admin/ChannelsController.php
- resources/views/admin/channels/_form.blade.php
- resources/views/admin/channels/index.blade.php
- tests/Feature/Admin/ChannelAdministrationTest.php
* Allow color to be set when creating/updating channels
* Show the color infront of name in the admin channel list
> Add color in channel admin page

- resources/views/layouts/app.blade.php
This PR fixes content overflowing the app div as shown on the screenshot below.
> Fix content overflows when page exceeds 100% height.
